### ISSUE TITLE
Medic-Revive

### ISSUE THREAD

**Issue by NichtTube** [Fuzzlemann/UCUtils#2]
Ich würde mir folgende Funktion wünschen:
Beim Rechtsklick auf eine Leiche wird automatisch der /revive Befehl ausgeführt :D

**Comment by Fuzzlemann** [comment]
Hinzugefügt mit dem Commit https://github.com/Fuzzlemann/UCUtils/commit/533990f09f7f6907c029a6f3a43682f4e513c9ac

Bitte einmal testen -> https://drive.google.com/file/d/1uJRQK2VA2NWZMbAxb7536HINODO29f3G/view?usp=drivesdk

**Comment by NichtTube** [comment]
Ich selber bin kein Medic,
hatte den Vorschlag nur im Medic Channel gehört und deshalb mal hier vorgeschlagen ^-^
Sorry
